name: Francinette CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  francinette-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git
          cd francinette
          python -m pip install -r requirements.txt

      - name: Run Francinette
        run: |
          ./francinette/tester.sh  > ./francinette_output.log 2>&1
      
      - name: Upload Francinette output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: francinette_output
          path: francinette_output.log
