name: Francinette CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  francinette-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: sudo apt-get install -y make gcc valgrind
              
      - name: Download Francinette
        run: |
          bash -c "$(curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh)"

      - name: Run Francinette
        run: |
          francinette  > ./francinette_output.log 2>&1
      
      - name: Upload Francinette output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: francinette_output
          path: francinette_output.log
